### ISSUE TITLE
Incompatibility with Moonrise

### ISSUE THREAD

**Issue by koffiato** [AxalotLDev/Async#27]
Unfortunately, updates to this mod introduced incompatibilities with https://github.com/Tuinity/Moonrise starting from version 1.4 Alpha 1, older versions such as 1.3 Alpha 1 work fine, however. It may be a good idea including this under relevant section of readme.

**Comment by wicivo** [comment]
starting with Async 0.1.0+rc3-1.21.1 on Modrinth in the Dependencies section it says that Moonrise is not compatible
![image](https://github.com/user-attachments/assets/cb7b0566-e1c2-4901-83ea-6de0d82a2b97)

**Comment by FurryMileon** [comment]
Currently not compatible with Moonrise, but in the future we may try to add support for it.
  
(P.S. For Moonrise to work with async, most of the code needs to be fixed not by us, but by the creators of Moonrise, because their code includes a core check that will crash the server if it detects other threads.)
